#!/usr/bin/env bash

set -o errexit
set -o nounset

declare -r debug='false'
declare -r tmpfile_file="/tmp/publish.$$.tmpfiles"

function make_temp_file
{
    local template="${1:-publish.$$.XXXXXX}"
    if [[ $template != *XXXXXX ]]
    then
        template="$template.XXXXXX"
    fi
    local tmp=$(mktemp -t "$template")
    echo "$tmp" >> "$tmpfile_file"
    echo "$tmp"
}

function now
{
    date '+%Y-%m-%d %H:%M:%S'
}

function pwarn
{
    echo "$(now) [warning]: $@" 1>&2
}

function perr
{
    echo "$(now) [error]: $@" 1>&2
}

function pinfo
{
    echo "$(now) [info]: $@"
}

function pdebug
{
    if [[ $debug == 'true' ]]
    then
        echo "$(now) [debug]: $@"
    fi
}

function errexit
{
    perr "$@"
    exit 1
}

function onexit
{
    if [[ -f $tmpfile_file ]]
    then
        for tmpfile in $(< $tmpfile_file)
        do
            pdebug "removing temp file $tmpfile"
            rm -f $tmpfile
        done
        rm -f $tmpfile_file
    fi
}

function gh_publish {
    if [[ -z $version_string ]]
    then
        errexit 'gh_publish: version_string required'
    fi
    if [[ ! -s $release_asset ]]
    then
        errexit "gh_publish: expected to find $release_asset in $PWD"
    fi

    local -r release_json="{
        \"tag_name\" : \"v$version_string\",
        \"name\" : \"Test Release Assets $version_string\",
        \"body\" : \"test-release-assets $version_string\nhttps://github.com/lukebakken/test-release-assets/blob/master/RELNOTES.md\",
        \"draft\" : false,
        \"prerelease\" : false
    }"

    pdebug "Release JSON: $release_json"

    local curl_content_file="$(make_temp_file)"
    local curl_stdout_file="$(make_temp_file)"
    local curl_stderr_file="$(make_temp_file)"

    curl -4so $curl_content_file -w '%{http_code}' -XPOST \
        -H "Authorization: token $(< $github_api_key_file)" -H 'Content-type: application/json' \
        'https://api.github.com/repos/basho/riak-nodejs-client/releases' -d "$release_json" 1> "$curl_stdout_file" 2> "$curl_stderr_file"
    if [[ $? != 0 ]]
    then
        errexit "curl error exited with code: '$?' see '$curl_stderr_file'"
    fi

    local -i curl_rslt="$(< $curl_stdout_file)"
    if (( curl_rslt == 422 ))
    then
        pwarn "Release in GitHub already exists! (http code: '$curl_rslt')"
        curl -4so $curl_content_file -w '%{http_code}' -XGET \
            -H "Authorization: token $(< $github_api_key_file)" -H 'Content-type: application/json' \
            "https://api.github.com/repos/lukebakken/test-release-assets/releases/tags/v$version_string" 1> "$curl_stdout_file" 2> "$curl_stderr_file"
        if [[ $? != 0 ]]
        then
            errexit "curl error exited with code: '$?' see '$curl_stderr_file'"
        fi
    elif (( curl_rslt != 201 ))
    then
        errexit "Creating release in GitHub failed with http code '$curl_rslt'"
    fi

    if [[ ! -s $curl_content_file ]]
    then
        errexit 'no release info to parse for asset uploads'
    fi

    # https://uploads.github.com/repos/lukebakken/test-release-assets/releases/1115734/assets{?name,label}
    local -r upload_url_with_name=$(perl -ne 'print qq($1\n) and exit if /"upload_url"[ :]+"(https:\/\/[^"]+)"/' "$curl_content_file")
    local -r upload_url="${upload_url_with_name/\{?name,label\}/?name=$release_asset}"

    local curl_content_file="$(make_temp_file)"
    local curl_stdout_file="$(make_temp_file)"
    local curl_stderr_file="$(make_temp_file)"

    curl -4so $curl_content_file -w '%{http_code}' -XPOST \
        -H "Authorization: token $(< $github_api_key_file)" -H 'Content-type: application/x-compressed, application/x-tar' \
        "$upload_url" --data-binary "@$release_asset" 1> "$curl_stdout_file" 2> "$curl_stderr_file"
    if [[ $? != 0 ]]
    then
        errexit "curl error exited with code: '$?' see '$curl_stderr_file'"
    fi

    curl_rslt="$(< $curl_stdout_file)"
    if (( curl_rslt != 201 ))
    then
        errexit "Uploading release assets to GitHub failed with http code '$curl_rslt'"
    fi
}

trap onexit EXIT

declare -r version_string="${1:-unknown}"

if [[ $version_string != [0-9].[0-9].[0-9] ]]
then
    errexit 'first argument must be valid version string in X.Y.Z format'
fi

declare -r github_api_key_file="$HOME/.ghapi"
if [[ ! -s $github_api_key_file ]]
then
    errexit "please save your GitHub API token in $github_api_key_file"
fi

# Validate commands
if ! hash curl 2>/dev/null
then
    errexit "'curl' must be in your PATH"
fi

declare -r release_asset='test-release-assets.tgz'
if [[ ! -f $release_asset ]]
then
    tar -czvf $release_asset LICENSE *.md
fi

republish=${2:-''}
if [[ $republish == 'republish' ]]
then
    gh_publish
    exit 0
fi

declare -r current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ $debug == 'false' && $current_branch != 'master' ]]
then
    errexit 'publish must be run on master branch'
fi

git push --tags
git push
gh_publish
